#!/bin/bash -e
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.


export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ ! -f "${OPENSHIFT_REPO_DIR}.openshift/magento/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=${OPENSHIFT_REPO_DIR}.openshift/magento/
else
    php ${OPENSHIFT_REPO_DIR}.openshift/magento/composer.phar self-update
fi

( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar install )

if [ "$OPENSHIFT_APP_DNS" == "$OPENSHIFT_GEAR_DNS" ]
then
  if [ -f "${OPENSHIFT_DATA_DIR}local.xml" ]; then
    mkdir -p ${OPENSHIFT_REPO_DIR}.openshift/magento
    cp ${OPENSHIFT_DATA_DIR}local.xml ${OPENSHIFT_REPO_DIR}.openshift/magento/local.xml
  fi

  if [ -d ${OPENSHIFT_DATA_DIR}media ]
  then
    mkdir -p ${OPENSHIFT_REPO_DIR}.openshift/magento
    cp -r ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}.openshift/magento/
  fi
fi
